// <auto-generated />
using System;
using KargoTakibi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KargoTakibi.Migrations
{
    [DbContext(typeof(KargoTakipContext))]
    partial class KargoTakipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("KargoTakibi.Models.Hareket", b =>
                {
                    b.Property<int>("HareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KargoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("HareketID");

                    b.HasIndex("KargoID");

                    b.ToTable("Hareketler");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.Property<int>("KargoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliciAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliciAdresi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliciIl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliciIlce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AliciTelefonu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Durum")
                        .HasColumnType("TEXT");

                    b.Property<string>("GondericiAd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GondericiAdresi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GondericiIl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GondericiIlce")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GondericiTelefonu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KullaniciID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TakipNo")
                        .HasColumnType("TEXT");

                    b.HasKey("KargoID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Kargolar");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KargoTakibi.Models.Hareket", b =>
                {
                    b.HasOne("KargoTakibi.Models.Kargo", "Kargo")
                        .WithMany("Hareketler")
                        .HasForeignKey("KargoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kargo");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.HasOne("KargoTakibi.Models.Kullanici", "Kullanici")
                        .WithMany("Kargolar")
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kargo", b =>
                {
                    b.Navigation("Hareketler");
                });

            modelBuilder.Entity("KargoTakibi.Models.Kullanici", b =>
                {
                    b.Navigation("Kargolar");
                });
#pragma warning restore 612, 618
        }
    }
}
